apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: work-server-webuser
  namespace: default
spec:
  rules:
  - services: ["work-server.default.svc.cluster.local"]
    methods: ["*"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-work-server-webuser
  namespace: default
spec:
  subjects:
  - properties:
      source.namespace: istio-system
  roleRef:
    kind: ServiceRole
    name: work-server-webuser
